(function(){
'use strict';
var info={
  name:{title:'Scenario name',description:'A label for this scenario. It does not affect any calculation.'},
  purchasePrice:{title:'Purchase price',description:'The property acquisition price before closing costs or renovation. It is the basis for the down payment, mortgage amount, and cap rate.'},
  renovation:{title:'Renovation',description:'Upfront cash for repairs, improvements, or make-ready work. It increases cash required but does not automatically increase rent or property value in this model.'},
  downPaymentPct:{title:'Down payment',description:'The percentage of purchase price paid in cash. The mortgage is purchase price minus this down payment. At 20% or more down, this model does not charge PMI.'},
  mortgageRate:{title:'Mortgage rate',description:'The annual interest rate for a fixed-rate, fully amortizing mortgage.'},
  closingCostsPct:{title:'Closing costs',description:'Estimated buyer closing costs as a percentage of purchase price. They are treated as upfront cash and are not financed.'},
  mortgageTerm:{title:'Mortgage term',description:'Choose a 15-, 20-, or 30-year fixed amortization period. A longer term lowers the monthly payment but pays principal down more slowly.'},
  pmiPct:{title:'PMI estimate',description:'A planning estimate for annual private mortgage insurance as a percentage of the original loan: none, 0.6%, 1.0%, or 1.5%. Actual PMI varies materially with credit, down payment, loan amount, and insurer. The model charges no PMI with 20% or more down and stops modeled PMI once the remaining mortgage balance reaches 80% of the original purchase price.'},
  rentMonthly:{title:'Monthly rent',description:'Scheduled year-1 rent before vacancy. Maintenance and CapEx reserves are calculated as percentages of this rent.'},
  vacancyPct:{title:'Vacancy',description:'The percentage of scheduled rent assumed lost to vacancy, turnover, or nonpayment.'},
  rentGrowthPct:{title:'Rent growth',description:'The compound annual increase applied to rent in the five-year operating outlook. It does not affect the current year.'},
  propertyTaxAnnual:{title:'Property taxes',description:'Annual year-1 real-estate taxes paid by the owner. They grow at the cost-growth assumption in the five-year outlook.'},
  insuranceAnnual:{title:'Insurance',description:'Annual year-1 landlord or property insurance. It grows at the cost-growth assumption in the five-year outlook.'},
  hoaMonthly:{title:'HOA',description:'Monthly condo, HOA, or association dues paid by the owner. They grow at the cost-growth assumption in the five-year outlook.'},
  utilitiesMonthly:{title:'Owner-paid utilities',description:'Monthly utilities that remain the owner’s responsibility, such as water, sewer, heat, electricity, trash, or common-area service.'},
  maintenancePct:{title:'Maintenance reserve',description:'A budgeting reserve for routine repairs and maintenance, expressed as a percentage of scheduled rent. It rises automatically as rent rises.'},
  capexPct:{title:'CapEx reserve',description:'A reserve for larger replacements such as roofs, HVAC, appliances, paving, or other long-lived systems, expressed as a percentage of scheduled rent.'},
  otherExpensesMonthly:{title:'Other owner costs',description:'A monthly catch-all for recurring owner expenses not represented elsewhere.'},
  expenseGrowthPct:{title:'Cost growth',description:'The annual growth rate applied to taxes, insurance, HOA, utilities, and other fixed owner costs in the five-year outlook. Maintenance and CapEx already rise with rent.'}
};
window.RENTAL_FIELD_INFO=info;
var order=['name','purchasePrice','renovation','downPaymentPct','mortgageRate','closingCostsPct','mortgageTerm','pmiPct','rentMonthly','vacancyPct','rentGrowthPct','propertyTaxAnnual','insuranceAnnual','hoaMonthly','utilitiesMonthly','maintenancePct','capexPct','otherExpensesMonthly','expenseGrowthPct'];
function escapeHtml(value){return String(value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function addStyles(){var style=document.createElement('style');style.textContent='.info-link{display:inline-flex;align-items:center;justify-content:center;width:15px;height:15px;margin-left:4px;vertical-align:-2px;border:1px solid #98a2b3;border-radius:50%;color:#667085;font-size:9px;font-weight:700;line-height:1;text-decoration:none;background:#fff}.info-link:hover,.info-link:focus{border-color:#3157d5;color:#3157d5;background:#eef2ff;outline:none}.help-shell{max-width:820px;margin:0 auto;padding:20px}.help-top{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:16px}.help-top h1{margin:0;font-size:24px}.help-top p{color:#667085;margin:5px 0 0}.help-back{white-space:nowrap}.help-list{display:grid;gap:8px}.help-entry{scroll-margin-top:12px;background:#fff;border:1px solid #dfe3ea;border-radius:10px;padding:12px}.help-entry:target{border-color:#3157d5;box-shadow:0 0 0 3px #eef2ff}.help-entry h2{font-size:14px;margin:0 0 4px}.help-entry p{margin:0;color:#475467;line-height:1.45;font-size:13px}@media(max-width:620px){.help-shell{padding:10px}.help-top{display:block}.help-top h1{font-size:20px}.help-back{display:inline-block;margin-top:8px}.help-entry{padding:10px}.help-entry p{font-size:12px}}';document.head.appendChild(style);}
function addInfoLinks(){var targets=document.querySelectorAll('[data-key],[data-choice-key]'),seen={};for(var i=0;i<targets.length;i++){var key=targets[i].getAttribute('data-key')||targets[i].getAttribute('data-choice-key'),item=info[key];if(!item||seen[key]&&targets[i].getAttribute('data-key')===null)continue;var field=targets[i].closest?targets[i].closest('.field'):null;if(!field||field.querySelector('.info-link[data-info-key="'+key+'"]'))continue;var label=field.querySelector('label');if(!label)continue;var link=document.createElement('a');link.className='info-link';link.setAttribute('data-info-key',key);link.href='descriptions.html#field-'+key;link.target='rental-field-help';link.rel='noopener';link.textContent='i';link.title=item.title+' — description';link.setAttribute('aria-label','Description of '+item.title+' (opens field guide)');label.insertAdjacentElement('afterend',link);seen[key]=true;}}
function renderDescriptions(){var list=document.getElementById('fieldDescriptions');if(!list)return;var html='';for(var i=0;i<order.length;i++){var key=order[i],item=info[key];html+='<section class="help-entry" id="field-'+key+'"><h2>'+escapeHtml(item.title)+'</h2><p>'+escapeHtml(item.description)+'</p></section>';}list.innerHTML=html;}
addStyles();addInfoLinks();renderDescriptions();
})();
